name: TestBotPerfectEnv
channels:
  - conda-forge
dependencies:
  - python=3.10.4
  - pip
  - pip:
      - discord.py
      - aiohttp
      - selenium
variables:
  TOKEN: "MTI4MTI3MjgwMDYzMTMyNDY3Mg.GcYceq.5AJ7nPX-J2A5ETuzYzF92fcPgU8L51_L_2tDPI"
  COOKIE: [
{
    "domain": ".facebook.com",
    "expirationDate": 1757315343.666306,
    "hostOnly": false,
    "httpOnly": false,
    "name": "c_user",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "100066239360158",
    "id": 1
},
{
    "domain": ".facebook.com",
    "expirationDate": 1760278274.516682,
    "hostOnly": false,
    "httpOnly": true,
    "name": "datr",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "kEaiZg2OoWajCUiydlm5VdT-",
    "id": 2
},
{
    "domain": ".facebook.com",
    "expirationDate": 1726384148,
    "hostOnly": false,
    "httpOnly": false,
    "name": "dpr",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "1.5",
    "id": 3
},
{
    "domain": ".facebook.com",
    "expirationDate": 1733555343.666453,
    "hostOnly": false,
    "httpOnly": true,
    "name": "fr",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "1bweUpj6zt0lhYZbx.AWXxH8b9Id2XptHf2F8mbRFSmiU.Bm3U2N..AAA.0.0.Bm3U2N.AWVU9htlndo",
    "id": 4
},
{
    "domain": ".facebook.com",
    "expirationDate": 1733409298.32286,
    "hostOnly": false,
    "httpOnly": true,
    "name": "m_page_voice",
    "path": "/",
    "sameSite": "lax",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "100066239360158",
    "id": 5
},
{
    "domain": ".facebook.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "presence",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "C%7B%22t3%22%3A%5B%5D%2C%22utc3%22%3A1725779348508%2C%22v%22%3A1%7D",
    "id": 6
},
{
    "domain": ".facebook.com",
    "expirationDate": 1760195641.527705,
    "hostOnly": false,
    "httpOnly": true,
    "name": "ps_l",
    "path": "/",
    "sameSite": "lax",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "1",
    "id": 7
},
{
    "domain": ".facebook.com",
    "expirationDate": 1760195641.527788,
    "hostOnly": false,
    "httpOnly": true,
    "name": "ps_n",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "1",
    "id": 8
},
{
    "domain": ".facebook.com",
    "expirationDate": 1760176705.51654,
    "hostOnly": false,
    "httpOnly": true,
    "name": "sb",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "50aiZvl7HHluOveL68G_N9i-",
    "id": 9
},
{
    "domain": ".facebook.com",
    "expirationDate": 1726384148,
    "hostOnly": false,
    "httpOnly": false,
    "name": "wd",
    "path": "/",
    "sameSite": "lax",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "2560x1279",
    "id": 10
},
{
    "domain": ".facebook.com",
    "expirationDate": 1757315343.666529,
    "hostOnly": false,
    "httpOnly": true,
    "name": "xs",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "42%3AryuFeVrGR19CfQ%3A2%3A1725616704%3A-1%3A-1%3A%3AAcXGQP1XZ9bdR3i6csABQoSHaA8WEctAzTk5XFKBkCE",
    "id": 11
}
]
